Repository ZupIT/beagle-docs, pull requests merged in 2021-06, with the labels that each got.

#602 fix: page custom widgets
  content/pt/resources/customization/beagle-for-ios/custom-widgets.md
  static/shared/custom-component-box-ios.png
Labels: ios

#641 fix: remove unnecessary github link from beagle-framework
  content/en/resources/customization/beagle-for-backend/beagle-framework.md
Labels: fix, update documentation

#640 fix: remove unnecessary link on beagle framework
  content/en/resources/customization/beagle-for-backend/beagle-framework.md
Labels: fix, update documentation

#685 bugfix: Upload Images workflow
  .github/workflows/S3-upload.yml
Labels: bug, fix

#683 bugfix: Upload Images CI
  .github/workflows/S3-upload.yml
Labels: bug, fix

#686 bugfix: Upload Images workflow
  .github/workflows/S3-upload.yml
Labels: bug, fix

#687 bugfix: Upload Images workflow
  .github/workflows/S3-upload.yml
Labels: bug, fix

#684 bugfix: Upload Images workflow
  .github/workflows/S3-upload.yml
Labels: bug
