Repository ZupIT/beagle-docs, pull requests merged in 2021-07, with the labels that each got.

#651 refactor: trying to improve main overview page of the doc
  content/en/overview.md
  content/pt/overview.md
Labels: tech writer review

#708 fix: beagle-grpc-repo-link
  content/en/resources/gRPC/beagle-grpc-backend.md
Labels: backend, fix, update documentation

#710 bugfix: playground does not working properly
  config/_default/config.toml
Labels: bug, update documentation

#712 bugfix on overview page in shortcode playground
  content/pt/overview.md
Labels: bug, fix, update documentation

#711 bugfix on overview page in playground shortcode
  content/pt/overview.md
Labels: bug, update documentation

#714 bugfix: add language in playground shortcode v1.9
  content/pt/_index.md
Labels: bug, fix, update documentation

#713 fix: add language in playground shortcode on home page
  content/pt/_index.md
Labels: bug, fix, update documentation

#715 hotfix: docs-beta links
  .github/workflows/beta-upload.yml
Labels: aws, bug, fix

#703 fix: New structure ios - Custom Widget
  content/en/ios/customization/custom-widget/_index.md
  content/en/ios/customization/custom-widget/custom-widget.md
  content/en/ios/customization/custom-widget/serverdrivencomponent-custom-widget.md
  content/pt/ios/customization/custom-widget/_index.md
  content/pt/ios/customization/custom-widget/custom-widget.md
  content/pt/ios/customization/custom-widget/serverdrivencomponent-custom-widget.md
  static/shared/custom-component-servendrivencomponent.png
Labels: ios

#653 fix: Customization Custom Action
  content/en/ios/customization/_index.md
  content/en/ios/customization/custom-actions/_index.md
  content/en/ios/customization/custom-actions/async-custom-action.md
  content/en/ios/customization/custom-actions/custom-action.md
  content/en/ios/customization/custom-actions/overview.md
  content/pt/ios/customization/custom-actions/async-custom-action.md
  content/pt/ios/customization/custom-actions/custom-action.md
  content/pt/ios/customization/custom-actions/overview.md
Labels: ios

#716 refactoring beagle-helpers
  content/en/ios/beagle-helpers/_index.md
  content/en/ios/beagle-helpers/beagle-defaults.md
  content/en/ios/beagle-helpers/beagle-scaffold.md
  content/en/ios/beagle-helpers/overview.md
  content/pt/ios/beagle-helpers/_index.md
  content/pt/ios/beagle-helpers/beagle-defaults.md
  content/pt/ios/beagle-helpers/beagle-scaffold.md
  content/pt/ios/beagle-helpers/overview.md
Labels: tech writer review

#717 feat: add beagle flutter documentation
  content/en/api/context/global-context.md
  content/en/get-started/installing-beagle/flutter.md
  content/en/get-started/using-beagle/flutter.md
  content/en/resources/customization/beagle-for-flutter/_index.md
  content/en/resources/customization/beagle-for-flutter/beagle-widget.md
  content/en/resources/customization/beagle-for-flutter/configuration.md
  content/en/resources/customization/beagle-for-flutter/customization/_index.md
  content/en/resources/customization/beagle-for-flutter/customization/actions.md
  content/en/resources/customization/beagle-for-flutter/customization/components.md
  content/en/resources/customization/beagle-for-flutter/customization/operations.md
  content/en/resources/customization/beagle-for-flutter/customization/overview.md
  content/en/resources/customization/beagle-for-flutter/design-system.md
  content/en/resources/customization/beagle-for-flutter/development.md
  content/en/resources/customization/beagle-for-flutter/localhost.md
  content/en/resources/customization/beagle-for-flutter/services/_index.md
  content/en/resources/customization/beagle-for-flutter/services/http-client.md
  content/en/resources/customization/beagle-for-flutter/services/image-downloader.md
  content/en/resources/customization/beagle-for-flutter/services/logger.md
  content/en/resources/customization/beagle-for-flutter/services/storage.md
  content/en/resources/customization/beagle-for-ios/_index.md
  content/en/resources/customization/beagle-for-react-native/_index.md
  content/en/resources/customization/beagle-for-web/advanced-topics/data-structure.md
  content/en/resources/customization/beagle-for-web/advanced-topics/lifecycles.md
  content/en/resources/customization/beagle-for-web/advanced-topics/renderer-api.md
  content/en/resources/customization/beagle-for-web/beagle-service-parameter.md
  content/pt/api/context/global-context.md
  content/pt/get-started/installing-beagle/flutter.md
  content/pt/get-started/using-beagle/flutter.md
  content/pt/resources/customization/beagle-for-flutter/_index.md
  content/pt/resources/customization/beagle-for-flutter/beagle-widget.md
  content/pt/resources/customization/beagle-for-flutter/configuration.md
  content/pt/resources/customization/beagle-for-flutter/customization/_index.md
  content/pt/resources/customization/beagle-for-flutter/customization/actions.md
  content/pt/resources/customization/beagle-for-flutter/customization/components.md
  content/pt/resources/customization/beagle-for-flutter/customization/operations.md
  content/pt/resources/customization/beagle-for-flutter/customization/overview.md
  content/pt/resources/customization/beagle-for-flutter/design-system.md
  content/pt/resources/customization/beagle-for-flutter/development.md
  content/pt/resources/customization/beagle-for-flutter/localhost.md
  content/pt/resources/customization/beagle-for-flutter/services/_index.md
  content/pt/resources/customization/beagle-for-flutter/services/http-client.md
  content/pt/resources/customization/beagle-for-flutter/services/image-downloader.md
  content/pt/resources/customization/beagle-for-flutter/services/logger.md
  content/pt/resources/customization/beagle-for-flutter/services/storage.md
  content/pt/resources/customization/beagle-for-ios/_index.md
  content/pt/resources/customization/beagle-for-react-native/_index.md
  content/pt/resources/customization/beagle-for-web/advanced-topics/lifecycles.md
  content/pt/resources/customization/beagle-for-web/advanced-topics/renderer-api.md
  content/pt/resources/customization/beagle-for-web/beagle-service-parameter.md
Labels: flutter, tech writer review, update documentation

#734 fix: flutter baseUrl examples
  content/en/flutter/customization/configuration.md
  content/en/flutter/customization/localhost.md
  content/en/flutter/getting-started.md
  content/pt/flutter/customization/configuration.md
  content/pt/flutter/customization/localhost.md
  content/pt/flutter/getting-started.md
Labels: bug, flutter
