Repository ZupIT/beagle-docs, pull requests merged in 2021-04, with the labels that each got.

#470 Hotfix/intalling beagle v1.6
  content/en/get-started/installing-beagle/backend.md
  content/en/get-started/using-beagle-helpers/ios/beagle-scaffold.md
  content/pt/get-started/using-beagle-helpers/iOS/beagle-scaffold.md
  content/pt/resources/live-preview.md
Labels: fix, update documentation

#485 Improved sentences and fixed some erros v1.6
  .gitignore
  content/en/get-started/installing-beagle/android.md
  content/en/get-started/installing-beagle/backend.md
  content/en/get-started/using-beagle-helpers/android/beagle-defaults.md
  content/en/get-started/using-beagle-helpers/android/beagle-scaffold.md
  content/en/get-started/using-beagle/android.md
  content/en/resources/customization/beagle-for-android/custom-widget/serverdrivencomponent-custom-widget.md
  content/en/tutorials/how-to-create-new-actions.md
  content/pt/get-started/installing-beagle/android.md
  content/pt/get-started/installing-beagle/backend.md
  content/pt/get-started/using-beagle-helpers/Android/beagle-defaults.md
  content/pt/get-started/using-beagle-helpers/Android/beagle-scaffold.md
  content/pt/get-started/using-beagle/android.md
  content/pt/resources/customization/beagle-for-android/custom-widget/serverdrivencomponent-custom-widget.md
  content/pt/tutorials/how-to-create-new-actions.md
Labels: fix, update documentation

#481 Improved sentences and fixed some erros main
  .gitignore
  content/en/get-started/installing-beagle/android.md
  content/en/get-started/installing-beagle/backend.md
  content/en/get-started/using-beagle-helpers/android/beagle-defaults.md
  content/en/get-started/using-beagle-helpers/android/beagle-scaffold.md
  content/en/get-started/using-beagle/android.md
  content/en/resources/customization/beagle-for-android/custom-widget/serverdrivencomponent-custom-widget.md
  content/en/tutorials/how-to-create-new-actions.md
  content/pt/get-started/installing-beagle/android.md
  content/pt/get-started/installing-beagle/backend.md
  content/pt/get-started/using-beagle-helpers/Android/beagle-defaults.md
  content/pt/get-started/using-beagle-helpers/Android/beagle-scaffold.md
  content/pt/get-started/using-beagle/android.md
  content/pt/resources/customization/beagle-for-android/custom-widget/serverdrivencomponent-custom-widget.md
  content/pt/tutorials/how-to-create-new-actions.md
Labels: fix, update documentation

#480 Update README.md
  README.md
Labels: update documentation

#487 Update/api send request example v1.6
  content/en/api/actions/sendrequest.md
  content/pt/api/actions/sendrequest.md
Labels: update documentation

#486 updates the api send-request example
  content/en/api/actions/sendrequest.md
  content/pt/api/actions/sendrequest.md
Labels: update documentation

#482 feat: adding styleId doc on container
  content/en/api/components/layout/container.md
  content/en/resources/style/ios.md
  content/pt/api/components/layout/container.md
  content/pt/resources/style/ios.md
Labels: enhancement, tech writer review, update documentation

#489 feat: iOS - Add SwiftPM support section in installing Beagle iOS
  content/en/get-started/installing-beagle/ios.md
  content/pt/get-started/installing-beagle/ios.md
Labels: ios, tech writer review, update documentation

#483 feat: adding additional data on remote
  content/en/api/actions/navigate/route/remote.md
  content/pt/api/actions/navigate/route/remote.md
Labels: tech writer review, update documentation

#491 feat: example custom component android with action
  content/en/resources/customization/beagle-for-android/custom-widget/custom-widget-with-action.md
  content/pt/resources/customization/beagle-for-android/custom-widget/custom-widget-with-action.md
  static/shared/date-picker-android.png
Labels: android

#494 docs: iOS - Update Yoga version
  content/en/get-started/installing-beagle/ios.md
  content/pt/get-started/installing-beagle/ios.md
Labels: ios

#495 feat: release notes 1.7.0
  content/en/release-notes.html
  content/pt/release-notes.html
Labels: Adoption
