Repository ZupIT/beagle-docs, pull requests merged in 2021-03, with the labels that each got.

#349 fix release notes links
  content/en/release-notes.html
  content/pt/release-notes.html
Labels: fix

#354 move playground json files to shared folder
  content/en/api/components/ui/button.md
  static/shared/en.json
  static/shared/pt.json
Labels: aws, fix, hugo

#358 fix playground path on generated json files
  bin/playground.ts
Labels: bug, fix, hugo

#368 fix: pt/contribute/beagle-docs.md
  content/pt/contribute/beagle-docs.md
Labels: fix, update documentation

#382 feat: adding accessibilityHeader to doc
  content/en/api/accessibility.md
  content/pt/api/accessibility.md
Labels: update documentation

#335 feat: updates simple form and text input
  content/en/api/components/forms/simple-form.md
  content/en/api/components/ui/textinput.md
  content/pt/api/components/forms/simple-form.md
  content/pt/api/components/ui/textinput.md
Labels: update documentation

#314 feat: adding BeagleView states to iOS doc
  content/en/resources/customization/beagle-for-ios/beagle-view.md
  content/pt/resources/customization/beagle-for-ios/beagle-view.md
Labels: ios, update documentation

#389 release: v1.6
  config/_default/config.toml
Labels: enhancement, priority

#348 Revert "Revert "refactor: update proguard documentation""
  content/en/resources/customization/beagle-for-android/proguard-configuration.md
  content/pt/resources/customization/beagle-for-android/proguard-configuration.md
Labels: fix, update documentation

#356 feat: adding default error view on iOS
  content/en/resources/customization/beagle-for-ios/custom-beagle-navigation-controller.md
  content/pt/resources/customization/beagle-for-ios/custom-beagle-navigation-controller.md
Labels: ios, update documentation

#403 Fix/sync with branch main
  .github/workflows/aws-s3.yml
  .github/workflows/hotfix.yml
Labels: fix

#404 fix version buttons
  config/_default/config.toml
Labels: fix

#411 update CI
  .github/workflows/S3-upload.yml
  .github/workflows/beta-upload.yml
  .github/workflows/prepare-release.yml
Labels: fix

#421 get versions from github api
  .github/workflows/build-check.yml
  config/_default/config.toml
  content/en/faq.md
  content/en/reference.md
  content/en/release-notes.md
  content/pt/faq.md
  content/pt/reference.md
  content/pt/release-notes.md
  layouts/partials/navbar-version-selector.html
Labels: fix, hugo

#420 get versions list from github api
  .github/workflows/build-check.yml
  config/_default/config.toml
  content/en/faq.md
  content/en/reference.md
  content/en/release-notes.md
  content/pt/faq.md
  content/pt/reference.md
  content/pt/release-notes.md
  layouts/partials/navbar-version-selector.html
Labels: fix, hugo

#419 Fix/dynamic versioning
  .github/workflows/S3-upload.yml
  .github/workflows/build-check.yml
  config/_default/config.toml
  content/en/faq.md
  content/en/reference.md
  content/en/release-notes.html
  content/en/release-notes.md
  content/pt/faq.md
  content/pt/reference.md
  content/pt/release-notes.html
  content/pt/release-notes.md
  layouts/partials/navbar-version-selector.html
Labels: aws, fix, hugo

#427 update release v1.5
  config/_default/config.toml
  content/en/faq.md
  content/pt/faq.md
  layouts/partials/navbar-version-selector.html
  layouts/partials/page-meta-links.html
  layouts/partials/search-input.html
Labels: fix, hugo

#426 Fix/faq and search label
  config/_default/config.toml
  content/en/faq.md
  content/pt/faq.md
  layouts/partials/navbar-version-selector.html
  layouts/partials/page-meta-links.html
  layouts/partials/search-input.html
Labels: fix, hugo

#425 Fix/faq and search label
  config/_default/config.toml
  content/en/faq.md
  content/pt/faq.md
  layouts/partials/navbar-version-selector.html
  layouts/partials/page-meta-links.html
  layouts/partials/search-input.html
Labels: fix, hugo

#437 unversioning FAQ
  config/_default/config.toml
  content/en/faq.md
  content/pt/faq.md
  layouts/partials/navbar.html
Labels: enhancement, hugo

#436 Feat/global faq
  .github/workflows/S3-upload.yml
  config/_default/config.toml
  content/en/faq.md
  layouts/partials/navbar.html
Labels: enhancement, hugo

#435 Feat/global faq
  .github/workflows/S3-upload.yml
  config/_default/config.toml
  content/en/faq.md
  layouts/partials/navbar.html
Labels: enhancement, hugo

#443 fix: faq
  .github/workflows/S3-upload.yml
  config/_default/config.toml
  layouts/partials/navbar-lang-selector.html
  layouts/shortcodes/iframe.html
Labels: fix

#446 hotfix: preview plugin link
  content/en/resources/live-preview.md
  content/pt/resources/live-preview.md
Labels: fix
